name: slack CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"  # 매일 오전 10시 (UTC 기준 → 한국 기준은 +9 시간)

jobs:
  post_announcement_message:
    runs-on: ubuntu-latest
    steps:
      - name: action code checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write google_creds.json
        run: echo "${{ secrets.GOOGLE_CREDS_JSON }}" > google_creds.json

      - name: run main.py
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        run: python3 main.py
